# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13ed48f6e11dfd2e4e66eaa4757e9ff1"
name = "ai-blog"
handle = "ai-blog-15"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_content,write_files"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
